### ISSUE TITLE
Docs missing from 5.6.0?

### ISSUE THREAD

**Issue by barjac** [j256/dmalloc#19] opened 2020-11-24 15:31 UTC
Hi, I maintain this package for Mageia and seem to be having problems finding the docs. Am I missing something or is the tarball missing something?

**Comment by j256** [comment] 2020-11-24 17:52
Huh.  This is a duplicate of https://github.com/j256/dmalloc/issues/17, fixed in https://github.com/j256/dmalloc/pull/18
I'm a little surprised that this Makefile target is used that much.  Can you explain how it is used?

**Comment by j256** [comment] 2020-11-24 18:10
I just released 5.6.1 of the library with a fix to the installdocs target.  Let me know if it works @barjac .

**Closed by j256** 2020-11-24 18:10 UTC

**Comment by barjac** [comment] 2020-11-25 15:28
Yes that now builds OK thanks. Your question about how it is used I can only answer by pointing you to the current rpm spec.
http://svnweb.mageia.org/packages/cauldron/dmalloc/current/SPECS/dmalloc.spec?revision=1649202&view=markup
I can't recall how I ended up maintaining this package, and I know very little about it. We build for x86 (64&32bit) aarch64 and armv7. If you have any advice or improvement to the way we are building, then please let me know. Thanks, Barry

**Comment by j256** [comment] 2020-11-25 18:17
Well glad it worked Barry and thanks for your work on Mageia.  You spec file LGTM.
